export const GET_UNDERLYING_SUCCESS = "GET_UNDERLYING_SUCCESS";
export const GET_UNDERLYING_FAILURE = "GET_UNDERLYING_FAILURE";
export const GET_DERIVATIVES_SUCCESS = "GET_DERIVATIVES_SUCCESS";
export const GET_DERIVATIVES_FAILURE = "GET_DERIVATIVES_FAILURE";